### ISSUE TITLE
Update report summary text

### ISSUE THREAD

**Issue by mattgarner** [eastgenomics/eggd_vcf2xls_nirvana#10]

**Comment by mattgarner** [comment]
Remove decimal places from panel coverage

**Comment by mattgarner** [comment]
Change coverage text

**Comment by mattgarner** [comment]
> Change coverage text

"99% of this panel was sequenced to a depth of 20X or greater (including homologous regions where reads do not map uniquely), with analytical sensitivity of 98.3% - 100% (95% Confidence Intervals)."

**Comment by woook** [comment]
Please round % down to nearest whole percent, i.e. 99.99 -> 99

**Comment by woook** [comment]
Updated workding:

99% of this panel was sequenced to a depth of 20X or greater (this includes homologous regions where reads do not map uniquely), with analytical sensitivity of 99.5-99.9% (95% confidence interval from benchmarking against GIAB HG001 reference material).

**Comment by Yu-jinKim** [comment]
I noticed that the report text is not really readable in normal excel:
![image](https://user-images.githubusercontent.com/25991776/82053087-a719ff80-96b4-11ea-820a-d063a1eb0372.png)

When the actual cell contains this:
![image](https://user-images.githubusercontent.com/25991776/82053123-b7ca7580-96b4-11ea-89f8-53e9e1afe002.png)

I probably need to fix that

**Comment by mattgarner** [comment]
This is a single block of text which is copied into the clinical report, so unfortunately needs to stay in a single cell please. 

Sorry I didn't see this comment before you made your changes.
