### ISSUE TITLE
Reads QC missing from summary sheet

### ISSUE THREAD

**Issue by mattgarner** [eastgenomics/eggd_vcf2xls_nirvana#2]
Need to update to extract this from output files in rather than database as previously, since database is not accessible from DNAnexus

**Comment by Yu-jinKim** [comment]
Add flagstat file in the inputs to extract total nb of reads and nb aligned

**Comment by Yu-jinKim** [comment]
Fixed in https://github.com/eastgenomics/eggd_vcf2xls_nirvana/commit/9aa7276844840acaf17496cb2bbcae9add29d533
