### ISSUE TITLE
Software versions missing from summary sheet

### ISSUE THREAD

**Issue by mattgarner** [eastgenomics/eggd_vcf2xls_nirvana#3]
Cannot be pulled from database since this is not accessible from DNAnexus.

Might be better to replace this with workflow versions, since this captures all versions of software contained within it.

**Comment by Yu-jinKim** [comment]
`dx describe` the vcf for example and `dx describe` the analysis-id under root execution field to get the workflow version

**Comment by Yu-jinKim** [comment]
Fixed in https://github.com/eastgenomics/eggd_vcf2xls_nirvana/commit/9aa7276844840acaf17496cb2bbcae9add29d533
