### ISSUE TITLE
Samples not processed via DNAnexus have no job-id and fails

### ISSUE THREAD

**Issue by jethror1** [eastgenomics/eggd_vcf2xls_nirvana#33]
Tried running vcf2xls with vcfs that were generated outside of DNAnexus & therefore have no job-id attached to them, causes the following to happen and the app fails:

++ dx describe --delim _ Sample16.refseq_nirvana_203.annotated.vcf
++ grep job-
++ cut -d_ -f2
+ job_id=

Needs a default job id or similar setting to allow it to continue.

**Comment by Yu-jinKim** [comment]
Either we can have another option to specify whether it's a dnanexus vcf or check if the dx describe returns anything and continue without the job id. Need Matt's input on that I think

**Comment by jethror1** [comment]
Fixed by checking the returned dx describe for job id, if not present sets id's to "Unknown" which is then in the output file.

Changes in fix_id_bug branch.
