### ISSUE TITLE
Unique report names

### ISSUE THREAD

**Issue by mattgarner** [eastgenomics/eggd_vcf2xls_nirvana#5]
App currently calls samples sampleID.xls

When multiple reports are generated for the same sample these need to have distinct names so that they can co-exist in the same directory within a windows filesystem.

**Comment by Yu-jinKim** [comment]
On hold for now in https://github.com/eastgenomics/eggd_vcf2xls_nirvana/commit/16c3af4a71a068a084759b50d6264816dbf36589
